name: Release prometheus-varnish-exporter
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.4

  release:
    name: Release the artifacts
    runs-on: ubuntu-latest
    needs: [setup]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          ./build.sh ${{ github.ref_name }}
      - name: Create GitHub Release and upload assets
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }} created automatically by GitHub Actions.
          token: ${{ secrets.GITHUB_TOKEN }}
          make_latest: true
          prerelease: false
          draft: false
          files: |
            bin/release/dashboards-${{github.ref_name}}.tar.gz
            bin/release/prometheus_varnish_exporter-${{github.ref_name}}.darwin-amd64.tar.gz
            bin/release/prometheus_varnish_exporter-${{github.ref_name}}.freesbsd-amd64.tar.gz
            bin/release/prometheus_varnish_exporter-${{github.ref_name}}.linux-amd64.tar.gz
            bin/release/prometheus_varnish_exporter-${{github.ref_name}}.netbsd-amd64.tar.gz
            bin/release/prometheus_varnish_exporter-${{github.ref_name}}.openbsd-amd64.tar.gz
            bin/release/prometheus_varnish_exporter-${{github.ref_name}}.windows-amd64.tar.gz
            bin/release/sha256sums.txt

